
package gui;
import javax.swing.*;


public class BemVindo extends JFrame {

    /**
     * Creates new form BemVindo
     */
    public BemVindo(){
        initComponents();
        setLocationRelativeTo(null);
    }
   

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTPaciente = new javax.swing.JButton();
        BTMedico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setText("Paciente");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 210, 60, 20);

        jLabel2.setText("Médico");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 210, 40, 14);

        BTPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/clinica/imagens/paciente.png"))); // NOI18N
        BTPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(BTPaciente);
        BTPaciente.setBounds(250, 80, 100, 110);

        BTMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/clinica/imagens/medico.png"))); // NOI18N
        BTMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(BTMedico);
        BTMedico.setBounds(40, 80, 100, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/clinica/imagens/papelDeParede.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMedicoActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BTMedicoActionPerformed

    private void BTPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTPacienteActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_BTPacienteActionPerformed
    
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BemVindo().setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTMedico;
    private javax.swing.JButton BTPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
